title: fully fuller
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: create. share. repeat.
color:
  saturation: 0.8107769
  brandStrength: 0.2499894052743912
  lightness: 0.5100251
  brandColors:
    - '#000000'
    - '#0281D8'
    - '#C5C5C3'
    - '#F3F7F8'
    - '#AD2E6A'
  rhythmicContrast: 0.9348371
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f40598d-d3dd-4d9a-86ea-d93f8dbc6331.png
name: fullyfuller
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/86aff9b1-9c8d-444e-8c42-6404bfe12591.png
typography_spectrum: 0.2713033
layout_spectrum: 0.9548872
